/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

apply plugin: 'elasticsearch.internal-es-plugin'
apply plugin: 'elasticsearch.internal-cluster-test'

esplugin {
  name = 'ivf-hnsw-int8-vectors'
  description = 'IVF-HNSW-INT8 vector search format for Elasticsearch.'
  classname = 'org.elasticsearch.xpack.ivfhnswint8.IvfHnswInt8VectorsPlugin'
  extendedPlugins = ['x-pack-core']
}

dependencies {
  compileOnly project(path: xpackModule('core'))
  testImplementation(testArtifact(project(xpackModule('core'))))
  testImplementation(testArtifact(project(':server')))
}
